"""Add contracts table

Revision ID: efe1ee7bd1ee
Revises: df28a2b7cfad
Create Date: 2024-11-26 06:19:21.443954+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe1ee7bd1ee'
down_revision: Union[str, None] = 'df28a2b7cfad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
